language: go

go:
- "1.14"
- "1.15"
- "1.16"

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cover

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -package github.com/little-bird-finance/backend
