version: '3.1'

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

