FROM docker.io/golang:1.16.3 AS builder
RUN mkdir /app
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app cmd/main.go

FROM scratch
WORKDIR /bin
EXPOSE 3000
COPY --from=builder /app/app .
CMD [ "/bin/app" ]
