FROM docker.io/golang:1.16.3 AS builder
RUN mkdir /app
WORKDIR /app
RUN echo "nobody:x:65534:65534:Nobody:/:" > /etc_passwd
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app cmd/main.go

#FROM scratch
FROM alpine:latest
WORKDIR /bin/
#COPY --from=builder /etc_passwd /etc/passwd
COPY --from=builder /app/app .
#USER nobody
EXPOSE 3000
CMD [ "./app" ]
